{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "path = \"D:/tmp/desktop_old/Desktop/ElectroGame/Jalon 1/Project_Folder/\"\n",
    "trainFold = path + \"Training_Database/\"\n",
    "testFold = path + \"Testing_Database/\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "from os.path import isdir,isfile\n",
    "\n",
    "print(isdir(path))\n",
    "print(isdir(testFold))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Circle_1.png', 'Circle_10.png', 'Circle_100.png', 'Circle_101.png', 'Circle_102.png']\n",
      "Other_F_21.png\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.image.AxesImage at 0x1cc83c297b8>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAM0AAAD8CAYAAADUmiBhAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvOIA7rQAAEolJREFUeJzt3W2oZdV9x/Hvr9oEagNqHEXU21GZBLS00+RiA2JIapOqlIwWkjqUZNpKRyFCC31RTaANfVXaWCE0NSgRR0h9aK1xXpjWYSiRQm29kxgf4tNoTbzOMDOxRUMNTWf898XZx9meOeee/fz4+8Dl3rPPPuesfe/+3bX22muvrYjAzLL7mbYLYNY3Do1ZTg6NWU4OjVlODo1ZTg6NWU61hUbSFZKel7Rf0k11fY5Z01THeRpJJwEvAJ8A1oHHge0R8f3KP8ysYXXVNJcA+yPi5Yj4KXAvsK2mzzJr1Mk1ve85wKupx+vAry5a+YwzzojNmzfXVBSzbPbt2/ejiNi0bL26QqM5y97VDpS0E9gJsLKywtraWk1FMctG0g+yrFdX82wdOC/1+FzgQHqFiLg9IlYjYnXTpqXhNuuMukLzOLBF0vmS3gNcC+yu6bPMGlVL8ywijkq6Efhn4CTgzoh4po7PMmtaXcc0RMTDwMN1vb9ZWzwiwCwnh8YsJ4fGLCeHxiwnh8YsJ4fGLCeHxiwnh8YsJ4fGLCeHxiwnh8YsJ4fGLCeHxiwnh8YsJ4fGLCeHxiwnh8YsJ4fGLCeHxiynwqGRdJ6kf5H0rKRnJP1hsvxLkl6T9ETydVV1xTVrX5mJNY4CfxwR35H0PmCfpD3Jc7dGxJfLF8+sewqHJiIOAgeTn38s6Vkm09GaDVolxzSSNgO/Avx7suhGSU9KulPSaVV8hllXlA6NpJ8HHgD+KCLeBG4DLgS2MqmJblnwup2S1iStHTlyJMvnIM2bItqsWaVCI+lnmQTmGxHxjwARcSgijkXE28AdTG67cYKiczmPNTj+p9EdZXrPBHwdeDYi/jq1/OzUatcATxcv3nHpm09557E2lek9uxT4LPCUpCeSZV8AtkvayuTWGq8A15cqYUpEODDWujK9Z//K/PvQNDJ/syTquPWh2TK9GxEw20xzzWNN611ozNrWy9DMNstc21iTehkaODE4Zk3pbWhmubaxpvQ6NBHh8zfWuF6HZmpMwXGPYfsGERoY/jHO0LevTwYTmjT/J7Y6DSo0Y2qmWXsGFRpwcKx+gwuNWd0GGRrXNlanQYYG3Ntk9RlsaNJ8bsOqNOjQeGCn1WHQoQEHx6o3+NDAiWPUzMoYRWhmubaxMspMrAGApFeAHwPHgKMRsSrpdOA+YDOTyTU+ExH/XfazykpPzOE5Bqyoqmqaj0fE1ohYTR7fBOyNiC3A3uRxJ/gcjpVVV/NsG7Ar+XkXcHVNn2PWuCpCE8AjkvZJ2pksOyuZIH06UfqZsy/KOy1tlVzbWBmlj2mASyPigKQzgT2Snsvyooi4HbgdYHV1tfGDC088aEWVrmki4kDy/TDwIJO5mw9Np6dNvh8u+zl1cngsj7IToJ+S3NAJSacAn2Qyd/NuYEey2g7goTKfUxc306yIss2zs4AHkx3uZODvIuKfJD0O3C/pOuCHwKdLfk5tZruhp8u6zl3m7SkVmoh4GfjlOctfBy4v895N6svxTV/KOXSjHBGwjHdM24hDk/DATsvKoTHLyaFJ8YydloVDM4d7pWwjDs0Srm1slkOzgJtptohDswEHx+ZxaJZwcGyWQ5OBOwYszaHJybWNOTQZuZlmUw6NWU4OTQ6ztY1rnHFyaHJyp4A5NCW5thkfh6aALl9G4GZj/RyagrowItrhaEfhy50lfZDJ1LNTFwB/CpwK/AEwnczsCxHxcOESdlzTU91O39+BaU/h0ETE88BWAEknAa8xmcLp94BbI+LLlZSwB3zt/rhU1Ty7HHgpIn5Q0fv1lsMzfFWF5lrgntTjGyU9KelOSadV9Bnv6OLBbtvHN9ac0qGR9B7gU8DfJ4tuAy5k0nQ7CNyy4HWtzeVsVkYVNc2VwHci4hBARByKiGMR8TZwB5Npak8QEbdHxGpErG7atKnQB3etxnFtMw5VhGY7qabZdA7nxDVMpqmtVJfPk3jEwPCVmmFT0s8BnwCuTy3+S0lbmdyC45WZ5yoz22PVxWlau1imPuj69MBlp6V9C3j/zLLPlipRvs8HaPQ8SRZdmB+66zveIl1qNSwyiBEBXTyWaKsJ2beQpKV/R13ejkGEBvoRHFusL4GBAYUGuhmctC6WqWu6HhgYWGige8HpwsDOruvb72RwoYHuBQe6Waa2zZ5n60MtAwMNjVmdBhuaLl7P79rmuNnt70stAwMODXRz5ECfdo669DkwMPDQQDeDM9WlsjRl9himb4GBEYQGuteDVWVZ2t6WPPp40D/PKEIzNaTg9G2nG0pgYGShge4GZyyGsM2jCw10KzhTXenhq8PQtmuUoYHuBKfLHRVVGFKzbGq0oQEHp25DDAyMPDRmRZS6CK0ti/4TF/lv1oULxtKf2bUL6ooaai0DPQ3NIkXD1KVLp6ueeLDpben72f4sehmaeX+IjXa0jZ6bvleXglO2DG3N+DmGwEDGY5pk0r/Dkp5OLTtd0h5JLybfT0uWS9JXJO1PJgz8UF2FT5ue9Z/9Wmba1TtvJ2vrgLwrHRR5jCUwkL0j4C7gipllNwF7I2ILsDd5DJN50LYkXzuZTB7YmkVhyvpHTYeqyXMpfQwO9Hc8WR6ZQhMRjwL/NbN4G7Ar+XkXcHVq+d0x8Rhw6sxcaJ1RNFDzglRHoPqy8/Up1FUo0+V8VkQcBEi+n5ksPwd4NbXeerKsV+aFJ29zr8pAdXXHHHIv2SJ1nKeZ99c94bfZl7mcZ5tJZZp7RcLU5WbaGAMD5UJzaNrsSr4fTpavA+el1jsXODD74irmcm5K1h23ruZeF69CHWtgoFxodgM7kp93AA+lln8u6UX7CPDGtBlnNgSZztNIugf4GHCGpHXgz4C/AO6XdB3wQ+DTyeoPA1cB+4G3mNwZrfdmRw7k/e+6aP1ltcai59usbcZcy0DG0ETE9gVPXT5n3QA+X6ZQXVXHkJuNXp81GE2eIxl7YKCnIwLa1OTIgbwjHxatU8WOPqaTl8s4NAW0OeRmdmDnsuWzsgwpylqGsXJoCmp7VPKi8WXzwlNFoOw4h6aksh0EVX121vUXyfM+Yz+ucWgq0GZwpop87rJLKYocP817n6FxaCrSp+AsC8vsOlV3l/c9TA5NhboanOmyjY6BZtff6Pksz20UqL7XTp4jwCwn1zQVa6u2ma1J5vXuza4/T1UH+VU36cqWp0oOTQ3qGDmQR9Edr4lesTI9eF05RnJoatLGCdCNuqDzfHZb/9GrrJ3q3AaHpkZNBmeoF7lBdeeXquLQ1KzOkQMb1SpdHOxZhzbK69A0pKoOgqzHK1lOUPY9MG1xl3ODyly6vOyKzSxXh2702IHJzqFpWN7gLApL1nkJZt9r9nOLvM/YuXnWgixNtap6hDY6X+OwFOOaxiwnh6Yli5pp85pjVTShZl/vWqa4paHR/Hmc/0rSc5rM1fygpFOT5Zsl/UTSE8nX1+osfN8tm5rJxxvdlKWmuYsT53HeA/xiRPwS8AJwc+q5lyJia/J1QzXFHKaNzrNUdW3Moue7fDKz65aGJubM4xwRj0TE0eThY0wmBLQMpjVK0aHzs/JeP1Om29smqjim+X3gW6nH50v6rqRvS7qsgvcfhGVdx7O1S1U79LzAuMlXTqkuZ0lfBI4C30gWHQRWIuJ1SR8Gvinp4oh4c85rdzK5FQcrKytlitFZRQZP1jVyYNlgSAcpu8I1jaQdwG8Cv5NMEEhE/G9EvJ78vA94CfjAvNdHj+ZyzqvsCcmyNU6WwMy7utOyKRQaSVcAfwJ8KiLeSi3fJOmk5OcLmNzY6eUqCtoHG/WA5f1PXjQ4eYbHODjFLG2eaf48zjcD7wX2JL/ox5Keso8Cfy7pKHAMuCEiZm8GNTh1Xc9RpqmWdd06R2EP1dLQxPx5nL++YN0HgAfKFsqsyzwioKBFXcdVn5DM00wr07xy7ZKdB2zm0NakD3kuKquiLG6ibcw1TQYbnYxseqhL2etqNuITn9k4NBtY1hvWZFgW9XRVPdTfwVnOoZmjq4Mnm+oibns7u87HNImuzKm1TJZr/6vk45sTjT40fQnLVFNhyXqOaIzDcEYbmrpOSDYpb69amfcfYzgWGd0xTVePV7JYFvQ6ArTRcdRYOwpGFxqzsgbfPGvrhGTV8gz1r3q7ljUD+/R7rMJgQzOkP3LeczF193iNvUdtcKEZwgF+WpbAzKsJqj5w32j+tLEZzDFNnw/wFylytr/uE6CeCqrnNU3fzrHkUWZ4zGzNM/bmVNV6WdOUvZy466oYT1bXRB2zxthM61Vohh6WWX0ZgDm24PSieTa0g/uN1HWCssrLmecFcUxNwE7XNEM8uF9kdlvrONeS/qw63ncsis7l/CVJr+n4nM1XpZ67WdJ+Sc9L+o26Cm7WlqJzOQPcGsfnbH4YQNJFwLXAxclr/nY6pVNZQ61hoLm7ktV9fDOWY5tCczlvYBtwbzJp4H8C+4FLihaujSskm9ZUYOa9f1U7+ex7Dj08ZY5pbtTkVht3SjotWXYO8GpqnfVk2Qkk7ZS0JmntyJEjJYrRX7PHME39c6hjJx/TxINFQ3MbcCGwlcn8zbcky+f9pubuCUOeljaLOg/6s6hjJx9LcAqFJiIORcSxiHgbuIPjTbB14LzUqucCB8oVcXjaDsyiz64qOENuTkPxuZzPTj28Bpj2rO0GrpX0XknnM5nL+T/KFXG4urBz1T1yYIi1TdG5nD8maSuTptcrwPUAEfGMpPuB7zO5BcfnI+JYPUXvp67uRHWcAB3qiU91YWNWV1djbW2t7WLUrs5mWVWXAlRdxq40RbOQtC8iVpet1+kRAWZd5NA0pC//cas+vunythbl0NSs7jFldairY6Crx3N5OTQ1avps/7zPLKrK4AxtfmiHpiZtDo+p4z3LjhzoQw2blUNTg7aGx9ShyhOgff9dTDk0NRrCDgLjGR6TlUNTsaHuUE3NOdAHDk2F+tZLVoSD49BUZgyBmRp7cBwas5wcmgqMqZaZGnNt49CUNMbATI01OA5NQX0cHlOHMQbHoSmgjeExWbR18tATa1guXQlM28Z0AtShyWnIO0NZYwmOQ5PDkMaU1WUMIweKTkt7X2pK2lckPZEs3yzpJ6nnvlZn4Zvkg/58hhycLHcNuAv4G+Du6YKI+O3pz5JuAd5Irf9SRGytqoBd48BkN9TJNZaGJiIelbR53nOa/EY+A/xatcUy666yxzSXAYci4sXUsvMlfVfStyVdVvL9O8PHMMUMsZlW9qZO24F7Uo8PAisR8bqkDwPflHRxRLw5+0JJO4GdACsrKyWLYV02tGZa4ZpG0snAbwH3TZcldwt4Pfl5H/AS8IF5rx/7XM5jM6Qap0zz7NeB5yJifbpA0qbp/WgkXcBkWtqXyxXRhmIowcnS5XwP8G/AByWtS7oueepa3t00A/go8KSk7wH/ANwQEVnvbWMjMIQhN1l6z7YvWP67c5Y9ADxQvlg2ZOljHOjfcY5HBFgr+jzkxqGx1vR1yI1DY63rW3AcGrOcHBrrhD7VNg6NdUZfguPQWKf0ITgOjXVO14Pj0FgndXnkgENjndXVUQJlLw0wq1UXg+Oaxiwnh8YsJ4fGLCeHxiwnh8YsJ4fGLCeHxiwndaEfXNIR4H+AH7VdlpqcwXC3DYazfb8QEUunRupEaAAkrUXEatvlqMOQtw2Gv32z3Dwzy8mhMcupS6G5ve0C1GjI2wbD37536cwxjVlfdKmmMeuF1kMj6QpJz0vaL+mmtstTheTucE8ld4NbS5adLmmPpBeT76e1Xc6sFtwNb+72aOIryd/zSUkfaq/k9Wg1NMlk6V8FrgQuArZLuqjNMlXo4xGxNdUVexOwNyK2AHuTx31xF3DFzLJF23Mlk4nvtzC5lcptDZWxMW3XNJcA+yPi5Yj4KXAvsK3lMtVlG7Ar+XkXcHWLZcklIh4FZieyX7Q924C7Y+Ix4FRJZzdT0ma0HZpzgFdTj9eTZX0XwCOS9iU3rwI4KyIOAiTfz2ytdNVYtD1D/Zu+o+3LnefNljCE7rxLI+KApDOBPZKea7tADRrq3/Qdbdc068B5qcfnAgdaKktlIuJA8v0w8CCTZuihaTMl+X64vRJWYtH2DPJvmtZ2aB4Htkg6X9J7mNwoanfLZSpF0imS3jf9Gfgk8DST7dqRrLYDeKidElZm0fbsBj6X9KJ9BHhj2owbjOntDtr6Aq4CXmByf84vtl2eCrbnAuB7ydcz020C3s+kl+nF5PvpbZc1xzbdw+QmxP/HpCa5btH2MGmefTX5ez4FrLZd/qq/PCLALKe2m2dmvePQmOXk0Jjl5NCY5eTQmOXk0Jjl5NCY5eTQmOX0/7EEROKuSQ3uAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "from os import listdir\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "\n",
    "import random\n",
    "\n",
    "imList = listdir(trainFold)\n",
    "print(imList[0:5])\n",
    "\n",
    "\n",
    "print(random.choice(imList))\n",
    "im = Image.open(trainFold + random.choice(imList))\n",
    "plt.imshow(im)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sknn.mlp import Classifier, Convolution, Layer\n",
    "\n",
    "nn = Classifier(\n",
    "    layers=[\n",
    "        Convolution(\"Rectifier\", channels=8, kernel_shape=(3,3)),\n",
    "        Convolution(\"Rectifier\", channels=16, kernel_shape=(3,3)),\n",
    "        Layer(\"Softmax\")],\n",
    "    learning_rate=0.02,\n",
    "    n_iter=5)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "Traceback (most recent call last):\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 58, in <module>\n    from tensorflow.python.pywrap_tensorflow_internal import *\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n    _pywrap_tensorflow_internal = swig_import_helper()\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\imp.py\", line 242, in load_module\n    return load_dynamic(name, filename, file)\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\imp.py\", line 342, in load_dynamic\n    return _load(spec)\nImportError: DLL load failed: Le module spécifié est introuvable.\n\n\nFailed to load the native TensorFlow runtime.\n\nSee https://www.tensorflow.org/install/errors\n\nfor some common reasons and solutions.  Include the entire stack trace\nabove this error message when asking for help.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     57\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 58\u001b[1;33m   \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[1;33m*\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     59\u001b[0m   \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0m__version__\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     27\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0m_mod\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 28\u001b[1;33m     \u001b[0m_pywrap_tensorflow_internal\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     29\u001b[0m     \u001b[1;32mdel\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36mswig_import_helper\u001b[1;34m()\u001b[0m\n\u001b[0;32m     23\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 24\u001b[1;33m                 \u001b[0m_mod\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mimp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mload_module\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'_pywrap_tensorflow_internal'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfp\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpathname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     25\u001b[0m             \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\imp.py\u001b[0m in \u001b[0;36mload_module\u001b[1;34m(name, file, filename, details)\u001b[0m\n\u001b[0;32m    241\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 242\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mload_dynamic\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilename\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    243\u001b[0m     \u001b[1;32melif\u001b[0m \u001b[0mtype_\u001b[0m \u001b[1;33m==\u001b[0m \u001b[0mPKG_DIRECTORY\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\imp.py\u001b[0m in \u001b[0;36mload_dynamic\u001b[1;34m(name, path, file)\u001b[0m\n\u001b[0;32m    341\u001b[0m             name=name, loader=loader, origin=path)\n\u001b[1;32m--> 342\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0m_load\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mspec\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    343\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mImportError\u001b[0m: DLL load failed: Le module spécifié est introuvable.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-1-64156d691fe5>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mtensorflow\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     22\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     23\u001b[0m \u001b[1;31m# pylint: disable=g-bad-import-order\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 24\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mpywrap_tensorflow\u001b[0m  \u001b[1;31m# pylint: disable=unused-import\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     25\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     26\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_api\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mv1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mapp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     47\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     48\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 49\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mpywrap_tensorflow\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     50\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     51\u001b[0m \u001b[1;31m# Protocol buffers\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     72\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0msome\u001b[0m \u001b[0mcommon\u001b[0m \u001b[0mreasons\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0msolutions\u001b[0m\u001b[1;33m.\u001b[0m  \u001b[0mInclude\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mentire\u001b[0m \u001b[0mstack\u001b[0m \u001b[0mtrace\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     73\u001b[0m above this error message when asking for help.\"\"\" % traceback.format_exc()\n\u001b[1;32m---> 74\u001b[1;33m   \u001b[1;32mraise\u001b[0m \u001b[0mImportError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     75\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     76\u001b[0m \u001b[1;31m# pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mImportError\u001b[0m: Traceback (most recent call last):\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 58, in <module>\n    from tensorflow.python.pywrap_tensorflow_internal import *\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n    _pywrap_tensorflow_internal = swig_import_helper()\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\imp.py\", line 242, in load_module\n    return load_dynamic(name, filename, file)\n  File \"C:\\Users\\arman\\Anaconda3\\lib\\imp.py\", line 342, in load_dynamic\n    return _load(spec)\nImportError: DLL load failed: Le module spécifié est introuvable.\n\n\nFailed to load the native TensorFlow runtime.\n\nSee https://www.tensorflow.org/install/errors\n\nfor some common reasons and solutions.  Include the entire stack trace\nabove this error message when asking for help."
     ]
    }
   ],
   "source": [
    "import tensorflow as tf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[18, 10,  7, 19],\n",
       "       [17,  3, 11, 17],\n",
       "       [15, 12, 14, 21],\n",
       "       [15,  6,  9, 10]])"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from scipy import ndimage\n",
    "import numpy as np\n",
    "a = np.array([[1, 2, 0, 0], \\\n",
    "   [5, 3, 0, 4], \\\n",
    "   [0, 0, 0, 7], \\\n",
    "   [9, 3, 0, 0]]) \\\n",
    "\n",
    "k = np.array([[1,1,1],[1,1,0],[1,0,0]])\n",
    "from scipy import ndimage\n",
    "ndimage.convolve(a, k, mode='wrap', cval=0.0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
